create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.unify_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', company text not null default '',
  plan text not null default 'free' check (plan in ('free', 'pro', 'enterprise')),
  avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.unify_tools (
  id uuid primary key default gen_random_uuid(), slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  name text not null, description text not null, category text not null, icon text not null,
  color text not null check (color ~ '^#[0-9A-Fa-f]{6}$'), is_active boolean not null default true,
  sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.unify_projects (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade,
  tool_id uuid references public.unify_tools(id) on delete set null, title text not null check (char_length(title) between 1 and 180),
  status text not null default 'draft' check (status in ('draft', 'processing', 'completed', 'archived', 'failed')),
  content jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.unify_activities (
  id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
  project_id uuid references public.unify_projects(id) on delete cascade, tool_id uuid references public.unify_tools(id) on delete set null,
  action text not null check (action in ('created', 'updated', 'completed', 'archived', 'failed')),
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create index unify_projects_user_updated_idx on public.unify_projects(user_id, updated_at desc);
create index unify_activities_user_created_idx on public.unify_activities(user_id, created_at desc);
create index unify_projects_tool_idx on public.unify_projects(tool_id);
create index unify_activities_project_idx on public.unify_activities(project_id);
create index unify_activities_tool_idx on public.unify_activities(tool_id);

alter table public.unify_profiles enable row level security;
alter table public.unify_tools enable row level security;
alter table public.unify_projects enable row level security;
alter table public.unify_activities enable row level security;

create policy "unify_profiles_select_own" on public.unify_profiles for select to authenticated using ((select auth.uid()) = id);
create policy "unify_profiles_insert_own" on public.unify_profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "unify_profiles_update_own" on public.unify_profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "unify_tools_public_read" on public.unify_tools for select to anon, authenticated using (is_active = true);
create policy "unify_projects_select_own" on public.unify_projects for select to authenticated using ((select auth.uid()) = user_id);
create policy "unify_projects_insert_own" on public.unify_projects for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "unify_projects_update_own" on public.unify_projects for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "unify_projects_delete_own" on public.unify_projects for delete to authenticated using ((select auth.uid()) = user_id);
create policy "unify_activities_select_own" on public.unify_activities for select to authenticated using ((select auth.uid()) = user_id);
create policy "unify_activities_insert_own" on public.unify_activities for insert to authenticated with check ((select auth.uid()) = user_id);

grant select on public.unify_tools to anon, authenticated;
grant select, insert, update on public.unify_profiles to authenticated;
grant select, insert, update, delete on public.unify_projects to authenticated;
grant select, insert on public.unify_activities to authenticated;
grant usage, select on sequence public.unify_activities_id_seq to authenticated;

create or replace function private.set_unify_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;
create trigger set_unify_profiles_updated_at before update on public.unify_profiles for each row execute function private.set_unify_updated_at();
create trigger set_unify_tools_updated_at before update on public.unify_tools for each row execute function private.set_unify_updated_at();
create trigger set_unify_projects_updated_at before update on public.unify_projects for each row execute function private.set_unify_updated_at();

create or replace function private.handle_unify_new_user() returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.unify_profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(coalesce(new.email, ''), '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;
revoke all on function private.handle_unify_new_user() from public, anon, authenticated;
create trigger on_auth_user_created_unify after insert on auth.users for each row execute function private.handle_unify_new_user();

create or replace function private.log_unify_project_activity() returns trigger language plpgsql security definer set search_path = '' as $$
declare activity_action text;
begin
  if tg_op = 'INSERT' then activity_action := 'created';
  elsif new.status = 'completed' and old.status is distinct from new.status then activity_action := 'completed';
  elsif new.status = 'archived' and old.status is distinct from new.status then activity_action := 'archived';
  elsif new.status = 'failed' and old.status is distinct from new.status then activity_action := 'failed';
  else activity_action := 'updated'; end if;
  insert into public.unify_activities (user_id, project_id, tool_id, action, metadata)
  values (new.user_id, new.id, new.tool_id, activity_action, jsonb_build_object('title', new.title, 'status', new.status));
  return new;
end;
$$;
revoke all on function private.log_unify_project_activity() from public, anon, authenticated;
create trigger log_unify_project_activity after insert or update on public.unify_projects for each row execute function private.log_unify_project_activity();

insert into public.unify_tools (slug, name, description, category, icon, color, sort_order) values
('copywriter', 'Copywriter', 'Textos no tom da sua marca, organizados por projeto.', 'Conteúdo', 'DocumentText', '#D9FF6A', 10),
('image-generator', 'Gerador de imagens', 'Crie e organize visuais para campanhas e canais.', 'Criativo', 'Gallery', '#E6A6F7', 20),
('data-analysis', 'Análise de dados', 'Transforme dados do workspace em decisões claras.', 'Dados', 'Chart', '#93C5F7', 30),
('code-assistant', 'Assistente de código', 'Crie, revise e documente código no seu workspace.', 'Dev', 'Code', '#F9C765', 40),
('smart-chat', 'Chat inteligente', 'Converse com o contexto dos seus projetos e arquivos.', 'Atendimento', 'MessageText', '#FA9A84', 50),
('sales-proposals', 'Propostas comerciais', 'Monte propostas versionadas e acompanhe cada entrega.', 'Vendas', 'Briefcase', '#B7A8F5', 60)
on conflict (slug) do update set name=excluded.name, description=excluded.description, category=excluded.category,
icon=excluded.icon, color=excluded.color, sort_order=excluded.sort_order, is_active=true, updated_at=now();

insert into public.unify_profiles (id, full_name)
select id, coalesce(raw_user_meta_data ->> 'full_name', split_part(coalesce(email, ''), '@', 1)) from auth.users
on conflict (id) do nothing;
